# Generated by Django 3.2 on 2023-05-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='JH4SQ1DZ3G', max_length=100, null=True, verbose_name='Код подтверждения'),
        ),
    ]
